In [6]:
import matplotlib.pyplot as plt 
from sklearn.datasets import load_boston
from  sklearn.preprocessing import StandardScaler 
from  sklearn.linear_model import LinearRegression

In [7]:
X, y = load_boston(return_X_y=True)

C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Californi

In [8]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [9]:
scaler = StandardScaler()

In [17]:
scaled_X = scaler.fit_transform(X)

In [18]:
scaled_X

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [19]:
Ir=LinearRegression()

In [20]:
model = Ir.fit(scaled_X,y)

In [24]:
model.predict(X)

array([-2.77790220e+02, -2.05249620e+02, -1.87879574e+02, -1.44795275e+02,
       -1.51286773e+02, -1.54991946e+02, -3.38336431e+02, -3.62650225e+02,
       -4.13569743e+02, -3.66292873e+02, -3.72027947e+02, -3.42162752e+02,
       -3.55477883e+02, -3.39555153e+02, -3.59788324e+02, -3.41188450e+02,
       -3.42216350e+02, -3.70422623e+02, -4.43182028e+02, -3.53619199e+02,
       -4.02650272e+02, -3.61590677e+02, -3.75906918e+02, -3.83112756e+02,
       -3.70430742e+02, -4.49711051e+02, -3.80847144e+02, -4.48924635e+02,
       -3.61414177e+02, -3.64095214e+02, -4.23426937e+02, -3.72526865e+02,
       -5.49984209e+02, -4.07355694e+02, -5.07865312e+02, -2.75788343e+02,
       -2.99153578e+02, -2.74919581e+02, -2.82685980e+02, -1.28791995e+02,
       -1.19015484e+02, -1.80721157e+02, -1.87633221e+02, -1.84223152e+02,
       -1.96121588e+02, -1.91489162e+02, -2.05986389e+02, -2.27124823e+02,
       -2.70632923e+02, -2.16687983e+02, -2.02304367e+02, -1.87819976e+02,
       -1.69561695e+02, -

2nd method

In [29]:
import matplotlib.pyplot as plt 
from sklearn.datasets import load_boston
from  sklearn.preprocessing import StandardScaler 
from  sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [26]:
X, y = load_boston(return_X_y=True)

C:\Users\Lenovo\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Californi

In [ ]:
scaler = StandardScaler()

In [ ]:
Pipline([])